### ISSUE TITLE
Afficher le nombre d'upvotes d'un post

### ISSUE THREAD

**Issue by MrCodeMUN** [p-julien/discord-bot#12]
# Description

Afficher dans le titre d'un post le nombre d'upvotes reçus sur Reddit.

## Comportement actuel
![image](https://user-images.githubusercontent.com/32191782/130335539-bcf7366c-aa06-4103-ad37-b1413e77d6bf.png)

### Comportement n°1
![image](https://user-images.githubusercontent.com/32191782/130335569-aa707651-98d4-4fe9-8d87-7e9106830e3e.png)

**Comment by href404** [comment]
@MrCodeMUN Je me demande si on devrait pas intégrer l'affichage du nombre d'upvotes à la source du post lorsqu'on ajoute une réaction ℹ. Il en pense quoi le monsieur ?
